### Create User
POST http://localhost:3000/users
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiam9obmRvZUBnbWFpbC5jb20iLCJpYXQiOjE3MzI5Nzg1MjIsImV4cCI6MTczMjk4MjEyMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.YDpmEfbOkNGJLBmF46XRHCqbtUG9TfFcUT9HswBGllg

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe11@gmail.com",
  "password": "Password123!"
}


### Create Many Users
POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiam9obmRvZUBnbWFpbC5jb20iLCJpYXQiOjE3MzI5MDcwOTEsImV4cCI6MTczMjkxMDY5MSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.zCzRWLrNJ9J11rkqiCN-yv7WN6pXyqE0_-mYd8c9btE

{
  "users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "markdoe@gmail.com",
      "password": "Password123#"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tomdoe@gmail.com",
      "password": "Password123#"
    }
  ]
}
